### ISSUE TITLE
Linux Bug Report

### ISSUE THREAD

**Issue by nelwashere** [vBlackOut/VHackApi-Python-Official#2]
Traceback (most recent call last):
  File "./main.py", line 140, in <module>
    if attackneeded and AttackTournamentDB:
NameError: name 'AttackTournamentDB' is not defined

**Comment by ghost** [comment]
u need to disable the code for h4cksp4ce.de db. ist offline :/

**Comment by vBlackOut** [comment]
yes :) please redownload the official code on olympic 
https://github.com/OlympicCode/vHackXTBot-Python
