### ISSUE TITLE
NameError: name 'json_data' is not defined on CentOS 7

### ISSUE THREAD

**Issue by NandoPrates** [vBlackOut/VHackApi-Python-Official#3]
[root@centosrj VHackApi-Python-Official]# python main.py
Connexion Error try again...
Traceback (most recent call last):
  File "main.py", line 107, in <module>
    while len(json_data["data"]) > 1:
NameError: name 'json_data' is not defined

**Comment by NandoPrates** [comment]
# python -V
Python 2.7.5

**Comment by NandoPrates** [comment]
[root@centosrj VHackApi-Python-Official]# python -m pip install requests pytesseract futures Pillow tesseract console
Requirement already satisfied: requests in /usr/lib/python2.7/site-packages
Requirement already satisfied: pytesseract in /usr/lib/python2.7/site-packages
Requirement already satisfied: futures in /usr/lib/python2.7/site-packages
Requirement already satisfied: Pillow in /usr/lib64/python2.7/site-packages
Requirement already satisfied: tesseract in /usr/lib/python2.7/site-packages
Requirement already satisfied: console in /usr/lib/python2.7/site-packages
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python2.7/site-packages (from requests)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/lib/python2.7/site-packages (from requests)
Requirement already satisfied: idna<2.7,>=2.5 in /usr/lib/python2.7/site-packages (from requests)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /usr/lib/python2.7/site-packages (from requests)
Requirement already satisfied: olefile in /usr/lib/python2.7/site-packages (from Pillow)

**Comment by vBlackOut** [comment]
# the code is not updated 
please redownload and send request to official Olympic Code  in here 
https://github.com/OlympicCode/vHackXTBot-Python
